### PR TITLE
Update README.md to better reflect the installation process

### PR DESCRIPTION
**Pull request by juanmed**
I tried to collect all the errors and solutions found here and in other places to install your repository and put them into a single installation procedure.

About the dependencies, I tried you solution doing

wstool merge -t src mavros_controllers/dependencies.rosinstall
wstool update -t src -j4
rosdep install --from-paths src --ignore-src -y --rosdistro kinetic

but always got a "mavros_controllers/dependencies.rosinstall" not being a valid URL problem, so in the end, and for users who do not want to update other packages, simply wrote the process cloning the dependencies' repositories.

### CODE REVIEW

**Comment by juanmed** [comment]
I don't seem to get this right...

**Comment by juanmed** [comment]
I added  the process of deleting the original mavros downloaded when installing the px4 firmware and downloading the source files from mavros repo as indicated in #82

**Comment by Jaeyoung-Lim** [comment]
@juanmed This is awesome! Thank you for the contribution!

This has slipped on myside and will help a lot on people using this repo

**Comment by Jaeyoung-Lim** [comment]
I think there was a typo regarding the rosinstall

To see the working version, you can look into the installation process in `.travis` file

**Comment by juanmed** [comment]
Thanks. I will look at it and make a new pull request with changes next time.

**Comment by Jaeyoung-Lim** [comment]
@juanmed Awesome!

**Pull request merged**
