### PR TITLE
Rearrange some steps about attitude control  in acc2quaternion.

### PR DESCRIPTION
**Pull request by EdXian**

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@EdXian Thank you for the PR! Have you tested this?

I am observing some oscillations when I try and run this PR

**Comment by EdXian** [comment]
Hi @Jaeyoung-Lim ,
In my case, I  change the PID gain during the flight  and It works fine in my gazebo.
But I didnt change the default value in the base repository.

**Comment by Jaeyoung-Lim** [comment]
@EdXian Okay, So what you are saying is that I need to retune the controller?

**Comment by EdXian** [comment]
Hi @Jaeyoung-Lim ,
Maybe you can try this:
```
    Kpos_x_= 6.0;
    Kpos_y_= 6.0;
    Kpos_z_= 10.0;
    Kvel_x_= 1.5;
    Kvel_y_= 1.5;
    Kvel_z_= 3.33;
```

**Comment by EdXian** [comment]
Hi @Jaeyoung-Lim ,
My cowoker also tuned the PID gain for this package.  
Dose the drone still oscillate during the flight in your case?

**Comment by Jaeyoung-Lim** [comment]
@EdXian Yes, from the current master, when I apply this PR I get attitude oscillations.

**Comment by EdXian** [comment]
Hi @Jaeyoung-Lim ,
I think that we use different version of sitl_gazebo in PX4/Firmware.
When do you update your package last time?

**Comment by Jaeyoung-Lim** [comment]
@EdXian Okay, I will try updating my sitl_gazebo. Which launchfile are you using to check this?

**Comment by EdXian** [comment]
No, not yet.  I will do some test tommorrow if I have spare time.

**Comment by Jaeyoung-Lim** [comment]
@EdXian Cool, Thanks!

**Comment by Jaeyoung-Lim** [comment]
@EdXian Have you had a chance to test it with tracking the circular trajectory? I still have wierd behaviors when applying this PR, which I don't understand why it should be the case. It should only simply change the reference attitude

**Comment by EdXian** [comment]
Hi @Jaeyoung-Lim ,
Apologize that I am so busy in recent days that I can not give you a quick reply.
Dose the drone still fly weirdly with geometric controller in this PR?

**Comment by Jaeyoung-Lim** [comment]
@EdXian Yes, it flies fine. It was a problem in my local setup. Thanks for the contribution. I will also add a follow PR on being able to set the yaw being part of the FlatTarget topic.

**Pull request merged**
