### PR TITLE
[WIP] Enable flip on a trajectory

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR is a implementation of a reference that makes the quadrotor flip instantly.

This can be done by just giving a acceleration reference that is being rotated at a fixed position

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
Now starting to work!

[Flipping](https://youtu.be/yA6Z8EZ1iEA "Circular trajectory tracking")

**Comment by Jaeyoung-Lim** [comment]
Closing this as this is a stale PR and there is no plan to have this in master

**Comment by mzahana** [comment]
Hi @Jaeyoung-Lim ,
I was trying to figure out how a flip trajectory can be obtained and found this issue. . Is there a reason why this is not merged into master?

**Comment by Jaeyoung-Lim** [comment]
@mzahana This was just a fun project I did. I though it wasn't useful enough to be on master

**Pull request closed without merging**
